Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
    config.vm.provision "shell", inline: "su"
    config.vm.provision "shell", inline: "sudo echo '123456' | passwd --stdin root "
  
    config.vm.define "m1" do |m1|
        m1.vm.box = "centos/7"
        m1.vm.box_version = "1811.02"
        m1.vm.network "private_network", ip: "192.168.20.11"
        m1.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
    end
    
      
      config.vm.define "m2" do |m2|
        m2.vm.box = "centos/7"
        m2.vm.box_version = "1811.02"
        m2.vm.network "private_network", ip: "192.168.20.12"
        m2.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
      end
    
      config.vm.define "m3" do |m3|
        m3.vm.box = "centos/7"
        m3.vm.box_version = "1811.02"
        m3.vm.network "private_network", ip: "192.168.20.13"
        m3.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
      end
    
      config.vm.define "m4" do |m4|
        m4.vm.box = "centos/7"
        m4.vm.box_version = "1811.02"
        m4.vm.network "private_network", ip: "192.168.20.14"
        m4.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
    end
end